# font_family JetBrainsMonoNL Nerd Font
font_size 12.0



# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMonoNL Nerd Font' postscript_name=JetBrainsMonoNLNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 12.0

# Padding
# window_padding_width 12

# Transparencia (pywal lo va a overridear igual)
background_opacity 0.85

# Sin decoraciones de ventana propias
hide_window_decorations yes

# Cursor
shell_integration no-cursor
cursor_shape block
cursor_trail               3
cursor_trail_decay         0.1 0.4
cursor_trail_start_threshold 2
cursor_trail_color         none


# Scrollback
scrollback_lines 10000

# Copiar al seleccionar
copy_on_select yes

# Colores desde pywal (se regeneran automáticamente)
include ~/.cache/wal/colors-kitty.conf


shell zsh
